name = "mero"
license = "MIT"
licenselink = "https://github.com/darshanbaral/mero/blob/master/LICENSE"
description = "Theme for personal blogs"
homepage = "https://github.com/darshanbaral/mero"
demosite = "https://merodemo.netlify.app/"
tags = ["Personal", "Blog", "Dark"]
features = ["Responsive"]
min_version = "0.80.0"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"
